Thmz337 memo
thmz337/memo_app pull request #1
Opened 2024-05-12 13:49 UTC by thmz337

2024-05-19 16:09 UTC, u1tnk requested changes

2024-05-19 16:09 UTC, u1tnk commented on db.rb
> +    records = JSON.load_file(db, symbolize_names: true)
ここは readを呼べば良いですね。

2024-05-19 16:09 UTC, u1tnk commented on db.rb
> +  def self.read(db)
これでも良いですが複数 class methodを書くときは

```
class << self 
```
を使うと良いですね。

2024-05-19 16:09 UTC, u1tnk commented on memos.json
> +{"nextID":0,"memos":[]}
データファイルを リポジトリにコミットするのはNGです。 
削除した上生成されても gitからignoreされるようにしましょう。
また、プログラムから自動で生成されるべきです。

2024-05-19 16:09 UTC, u1tnk commented on app.rb
> +    set :db, './memos.json'
configureブロックを使ってるのは良いことなんですが、DBクラスのメソッドに毎回渡してるのはちょっと冗長に見えますが… せっかく configureブロック使ってるし、DBクラスに一回だけ渡す方法はオブジェクト指向のプラクティスの範囲なので、難しければ修正はしなくても良いです。

2024-05-20 14:39 UTC, thmz337 commented on db.rb
> +    records = JSON.load_file(db, symbolize_names: true)
readを呼ぶように変更しました

2024-05-20 14:41 UTC, thmz337 commented on app.rb
> +    set :db, './memos.json'
DBモジュールをクラスとして作成し直しました。DBクラスのinitializeメソッドにて渡すようにしています。

2024-05-22 02:04 UTC, u1tnk approved these changes
OKです！
ただ、 `.gitignore` への追加が以下のコミットに混ざっているのはあんまり良くないですね。DBファイル削除と一緒にするべきでした。

https://github.com/thmz337/memo_app/pull/1/commits/36186b6b40ff21831ab4e805f42f630b6ef94c95

だいぶ細かいし、今後気をつけましょうで大丈夫です 🙆‍♀️

2024-05-22 12:21 UTC, merged